services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
     - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: ${echo-rest-api-db}
    restart: always
    networks:
       - lesson
networks:
  lesson: